### PR TITLE
fix(samples): correct usage of toString()

### PR DESCRIPTION
**Pull request by anchor-crockagile**
I did not make a corresponding issue ticket because this seemed like a small documentation fix and 🤞 the lengthy issue template is not needed. But I can change this if needed!

When accessing a secret version, the payload data is of type `string | Uint8Array`, neither of which accepts a character encoding option in their `toString()` function.

I am not sure if this is done because there is maybe some third, undocumented possible type of payload (like a Buffer?).

- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-secret-manager/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by bcoe** [comment]
@anchor-crockagile bother you to sign the CLA? thanks for the contribution.

**Comment by anchor-crockagile** [comment]
@googlebot I signed it!

**Comment by anchor-crockagile** [comment]
@bcoe Looks like I broke the conventional commit/PR naming scheme. How can I fix that?

**Comment by stephenplusplus** [comment]
@anchor-crockagile there's plenty of info here: https://www.conventionalcommits.org/en/v1.0.0/. But basically, this should work: "fix(samples): correct usage of toString()"

**Comment by anchor-crockagile** [comment]
@stephenplusplus Thanks for your help! Is there anything else waiting on me for this PR?

**Comment by stephenplusplus** [comment]
Nope, I think I can take it from here. Thank you!

**Pull request merged**
