### PR TITLE
samples: Update getSecret sample to include version

### PR DESCRIPTION
**Pull request by OskarDamkjaer**
I struggled to get the samples running since I was missing `versions/*` which seems to be required now. I figured this change might help someone else in the future. Since just a small doc update so I felt it'd be overkill to open an issue, feel free to just close this PR if it's not helpful.

### CODE REVIEW

**Comment by bcoe** [comment]
@OskarDamkjaer are you able to sign the CLA, wo that we can merge this?

**Comment by OskarDamkjaer** [comment]
@bcoe on it! I'll write again when I've got it done, sorry bout the delay

**Comment by OskarDamkjaer** [comment]
@bcoe Signed!

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@OskarDamkjaer thank you for the contribution.

**Comment by sethvargo** [comment]
@bcoe please revert this change. `getSecret` operates on a _secret_ not a _secret version_. The original code was correct.

**Comment by sethvargo** [comment]
To get metadata about a secret _version_, use `getSecretVersion` (https://github.com/googleapis/nodejs-secret-manager/blob/main/samples/getSecretVersion.js). To _access_ a secret, use `accessSecret` (https://github.com/googleapis/nodejs-secret-manager/blob/main/samples/accessSecretVersion.js)

**Comment by OskarDamkjaer** [comment]
Ah it seems I found the wrong docs, sorry!

**Pull request merged**
