### PR TITLE
feat: add code samples for secret manager access by alias

### PR DESCRIPTION
**Pull request by nataliesalvati**
Update samples for Access By Alias Launch

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-secret-manager/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by sofisl** [comment]
Hi @nataliesalvati, can you add tests please? Thank you!

**Review by sofisl — CHANGES_REQUESTED** [review]
Hi @nataliesalvati, can you add tests please? Thank you!

**Comment by nataliesalvati** [comment]
> Hi @nataliesalvati, can you add tests please? Thank you!

Think I did this properly, sorry, JS isn't my strongsuit

**Comment by nataliesalvati** [comment]
> Hi @nataliesalvati, can you add tests please? Thank you!

Hey, I think I have this all fixed and ready, can you approve workflows?

**Review by sofisl — APPROVED** [review]

**Pull request merged**
